
# SEO settings
title: "Jatin K Malik - "
title2: "Engineering Blog" # default: ""
description: "Life of a software developer. Summarized. Also, expect to read about some regrets, tech debts, bad commits and programming karma in action."
keywords: ""
url: http://bitsnapper.com # site url
#baseurl: "" # apply repo name if use it under gh-pages branch
#baseurl: blog # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/jatinkrmalik/blog
disqus_shortname: "jatinkrmalik"
twitter_username: "jatinkrmalik"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jatin K Malik"
  job      : "SDE-II @ Shuttl"
  bio      : "This blog is all about life of a software developer - summarized! Expect to read about some regrets, tech debts, bad commits and programming karma in action."
  thumb    : /images/author.jpg
  email    : jatinkrmalik@gmail.com
  url      : http://jatinkrmalik.github.io/blog
  github   : http://github.com/jatinkrmalik
  twitter  : http://twitter.com/jatinkrmalik
  facebook : https://www.facebook.com/jk.malik
  linkedin : http://linkedin.com/in/jatinkrmalik

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@jatinkrmalik"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
